### PR TITLE
Updated handlers to support new Slack webhook structure

### PR DESCRIPTION
**Pull request by j0nes2k**
New webhook integrations use the URL scheme `https://hooks.slack.com/{path}`.

### CODE REVIEW

**Comment by bogdanr** [comment]
I tested this and it works fine. :+1:

**Comment by j0nes2k** [comment]
Feel free to merge this into your project then.

**Comment by ashiina** [comment]
Thanks for this, and sorry for the late reply. Looks good so I'll merge it :)

**Comment by frewsxcv** [comment]
@ashiina Still planning to merge this?

**Pull request merged**
